---
# Handlers pour le rôle webserver

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: true
  become: true

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  become: true

- name: test nginx config
  ansible.builtin.command:
    cmd: nginx -t
  become: true
  changed_when: false