---
# Collections Ansible requises pour le déploiement d'applications

collections:
  # Collection pour MySQL
  - name: community.mysql
    version: ">=3.0.0"

  # Collection générale avec modules utiles
  - name: community.general
    version: ">=6.0.0"

  # Collection pour la gestion des certificats
  - name: community.crypto
    version: ">=2.0.0"

  # Collection pour Posix (utilisateurs, fichiers, etc.)
  - name: ansible.posix
    version: ">=1.5.0"